// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAttackModes():Promise<Array<string>>;

export function GetSupportedFormats():Promise<Array<string>>;

export function SelectFile():Promise<string>;

export function StartCracking(arg1:string,arg2:string,arg3:Record<string, any>):Promise<main.CrackResult>;

export function ValidateArchive(arg1:string):Promise<boolean|string>;
