// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function ClearDictFilePath():Promise<void>;

export function GetAttackModes():Promise<Array<string>>;

export function GetAvailableThreadCounts():Promise<Array<number>>;

export function GetCPUInfo():Promise<config.CPUInfo>;

export function GetConfigPath():Promise<string>;

export function GetDictFilePath():Promise<string>;

export function GetLanguage():Promise<string>;

export function GetSupportedFormats():Promise<Array<string>>;

export function GetTheme():Promise<string>;

export function GetThreadCount():Promise<number>;

export function SelectDictFile():Promise<string>;

export function SelectFile():Promise<string>;

export function SetDictFilePath(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetThreadCount(arg1:number):Promise<void>;

export function StartCracking(arg1:string,arg2:string,arg3:Record<string, any>):Promise<main.CrackResult>;

export function ValidateArchive(arg1:string):Promise<boolean|string>;

export function ValidateDictFile(arg1:string):Promise<boolean|string>;
