// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAttackModes() {
  return window['go']['main']['App']['GetAttackModes']();
}

export function GetSupportedFormats() {
  return window['go']['main']['App']['GetSupportedFormats']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function StartCracking(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartCracking'](arg1, arg2, arg3);
}

export function ValidateArchive(arg1) {
  return window['go']['main']['App']['ValidateArchive'](arg1);
}
